"""Create a compact, auditable manifest of project resources and their sizes."""
from __future__ import annotations

import csv
import hashlib
import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT_DIR = ROOT / "reports"
REPORT_DIR.mkdir(parents=True, exist_ok=True)


def size_bytes(path: Path) -> int:
    if path.is_file():
        return path.stat().st_size
    total = 0
    for candidate in path.rglob("*"):
        try:
            if candidate.is_file():
                total += candidate.stat().st_size
        except OSError:
            # WSL venv links can be unreadable from native Windows; keep the
            # manifest auditable and record the accessible files.
            continue
    return total


def human(n: int) -> str:
    value = float(n)
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if value < 1024 or unit == "TiB":
            return f"{value:.2f} {unit}"
        value /= 1024
    return f"{n} B"


def sha256(path: Path) -> str:
    if not path.is_file() or path.stat().st_size > 200 * 1024 * 1024:
        return ""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def add(rows: list[dict], path: Path, kind: str, status: str, detail: str = "") -> None:
    rows.append(
        {
            "path": str(path.resolve()),
            "kind": kind,
            "status": status,
            "bytes": size_bytes(path),
            "size": human(size_bytes(path)),
            "sha256": sha256(path),
            "detail": detail,
        }
    )


rows: list[dict] = []

# Existing user inputs are explicitly separated from generated/downloaded content.
for name in ("DPPO.pdf", "图4.png", "图18.png"):
    path = ROOT / name
    if path.exists():
        add(rows, path, "input", "pre-existing", "supplied before this reproduction")

for name in ("README.md", "导师线上审阅说明.md", ".gitignore", ".gitmodules"):
    path = ROOT / name
    if path.exists():
        add(rows, path, "publication file", "created", "GitHub review material")

# Aggregate large runtime/cache directories; list their meaningful sub-artifacts separately.
for name, detail in (
    (".runtime", "project-local venv, MuJoCo runtime, gdown helper, mjrl"),
    (".cache", "project-local package cache"),
    (".tmp", "download/extraction temporary area; retained for audit"),
):
    path = ROOT / name
    if path.exists():
        add(rows, path, "directory aggregate", "created", detail)

for relative, detail in (
    (Path(".runtime") / "venv", "WSL Python virtual environment"),
    (Path(".runtime") / "mujoco210", "MuJoCo 2.1.0 runtime"),
    (Path(".runtime") / "gdown_tools", "Windows-side Google Drive downloader"),
    (Path(".runtime") / "mjrl_source", "third-party mjrl source checkout"),
    (Path(".cache") / "pip", "pip download/install cache"),
    (Path(".cache") / "torch", "torch cache"),
):
    path = ROOT / relative
    if path.exists():
        add(rows, path, "resource aggregate", "created", detail)

for path in sorted((ROOT / ".tmp").glob("*")) if (ROOT / ".tmp").exists() else []:
    if path.is_file():
        add(rows, path, "temporary file", "created/downloaded", "retained for audit")

for name in ("source", "data", "checkpoints", "logs", "results", "plots", "reports", "scripts"):
    path = ROOT / name
    if not path.exists():
        continue
    add(rows, path, "directory aggregate", "created", "recursive aggregate")
    for file_path in sorted(path.rglob("*")):
        try:
            is_file = file_path.is_file()
        except OSError:
            is_file = False
        if is_file:
            add(rows, file_path, "file", "created/downloaded", "")

rows.sort(key=lambda row: row["path"].lower())
csv_path = REPORT_DIR / "RESOURCE_MANIFEST.csv"
with csv_path.open("w", newline="", encoding="utf-8") as handle:
    writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
    writer.writeheader()
    writer.writerows(rows)

md_path = REPORT_DIR / "RESOURCE_MANIFEST.md"
with md_path.open("w", encoding="utf-8") as handle:
    handle.write("# Resource manifest\n\n")
    handle.write("Generated by `scripts/setup/inventory_resources.py`. Sizes are recursive for directory rows and exact for file rows. Native Windows skips unreadable WSL venv symlinks when summing aggregates; the manifest therefore reports accessible bytes for those aggregate rows.\n\n")
    handle.write("| Path | Kind | Status | Size | SHA256 (files <=200 MiB) | Detail |\n|---|---|---|---:|---|---|\n")
    for row in rows:
        digest = row["sha256"] or "-"
        detail = row["detail"].replace("|", "\\|")
        handle.write(f"| `{row['path']}` | {row['kind']} | {row['status']} | {row['size']} | `{digest}` | {detail} |\n")
    handle.write(f"\nTotal manifest rows: {len(rows)}.\n")

print(f"wrote {csv_path}")
print(f"wrote {md_path}")
print(f"rows={len(rows)}")
